apiVersion: v1
kind: Service
metadata:
  name: nginx-ebs-static
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30007 