apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboproject
  labels:
    name: nginx
    project: roboshop
spec:
  containers:
  - name: nginx
    image:  nginx
    ports:
    - containerPort:  80