apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image:  nginx
    resources:
      requests:
        memory: "68mi"
        cpu:  "100m"
      limits:
        memory: "100mi"
        cpu:  "120m"