apiVersion: v1
kind: Pod
metadata:
  name: Service-lb-demo
spec:
  selector:
    project:  roboshop
    component:  fronend
    environment:  dev
    purpose:  project-LoadBalancer
  containers:
  - name: nginx
    image:  nginx
