apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: res-demo
    project: roboshop

spec:
  replicas: 10
  selector:
    matchLabels:
      purpose: res-demo
      project: roboshop

  template:
    metadata:
      labels:
        purpose: res-demo
        project: roboshop

    spec:
      containers:
      - name: nginx
        image: nginx:latest