apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    purpose: dp-demo
    project: roboshop

spec:
  replicas: 5

  selector:
    matchLabels:
      purpose: dp-demo
      project: roboshop

  template:
    metadata:
      labels:
        purpose: dp-demo
        project: roboshop

    spec:
      containers:
      - name: nginx
        image: nginx:latest