apiVersion: v1
kind: Service
metadata:
  name: nginx-headles-clust
spec:
  # if a service clusterIP then it is called as headless service
  clusterIP: None
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port