apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-headless-svc
spec:
  clusterIP: None
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80